DELETE  http://localhost:3003/api/blogs/66b71dd7d6da92ad0b23446e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndyaXRlMTExIiwiaWQiOiI2NmE2M2E2ZWJjMzM1ZDRlNjFhYmYxYmUiLCJpYXQiOjE3MjMyMDk1MjR9.Kcf9r3ewZC-C-iMwIbp8bTqo3CvbMqisQt6YTWDuofE
content-type: application/json