POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndyaXRlMTExIiwiaWQiOiI2NmE2M2E2ZWJjMzM1ZDRlNjFhYmYxYmUiLCJpYXQiOjE3MjMyMDk1MjR9.Kcf9r3ewZC-C-iMwIbp8bTqo3CvbMqisQt6YTWDuofE

{
    "title": "man does a tester with user extractor 5",
    "author": "testman",
    "url": "blaablaa.com",
    "likes": 99
}